== upload_file_input_event

This sample application is designed to test the upload-file-name-input
events. This application receives uploaded file name input events and
leaves logs. For more details, refer to *1.6 Uploaded File Name Events*
in *Hanwha_Vision_Open_Platform_SDK_API*.

Related events are as follows:

*Receivable Events*

* Upload File Name Events + 
When a new file is uploaded to the
application, you can receive the application name and the name of the
new file via this event.
** Uploading files +
For more information on how to upload files, contact us. We will provide
you with the *SUNAPI* document that includes the information. When you
upload an application, the file is uploaded to the ./app folder within
the application.
+
....
$ curl -v --digest -u {ID}:{PASSWORD} -F "DataFile=@{UPLOAD FILE PATH};type=application/octet-stream" "http://{Camera IP}/stw-cgi/opensdk.cgi?msubmenu=apps&action=update&AppID={APP ID}" -H "Expect:"
....
*** {ID}, {PASSWORD}: Web page account
*** {UPLOAD FILE PATH}: Path of the file to upload
*** {DEVICE IP}: IP address of the device on which the application is
installed
*** {APP ID}: Name of the installed application to upload the file

=== Prerequisites

* SUNAPI compatible device
* Hanwha Vision Open Platform 23.00.00 or higher

=== Scenario

* Preconditions
[arabic]
. Open the camera web viewer, go to [Setup]>[Open Platform], and click
[Install] to install the application.
* Test
[arabic]
. Click [Start] in the camera web viewer to start the application.
. To view the results on the app's web page, upload a file to the
device. To upload the file in an environment that supports cURL, such as
the command prompt in Windows, run the following command. The 'DataFile'
field should contain the exact path where the file is located, and the
file must exist.
+
Example:
+
....
$ curl -v --digest -u testid:testpassword -F "DataFile=@test.txt;type=application/octet-stream" "http://192.168.38.59/stw-cgi/opensdk.cgi?msubmenu=apps&action=update&AppID=upload_file_input_event" -H "Expect:"
....
. Click [Go App] in the camera web viewer.
. Click [Get] on the application web page.
. Check the result.

=== Result

Go App

....
App name                  File name
upload_file_input_event   test.txt
....

=== Building Application

[arabic]
. Build application.
+
....
$ APP_NAME=upload_file_input_event SDK_VER=24.06.14(your SDK version) SOC=[cv5, orinnx8g_jp512] docker compose up
$ docker compose down --remove-orphans
....
. Check the build results in current directory. If successful, you will be able to find the cap file.
